In [50]:
import plotly.express as px
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# read excel file
df = pd.read_excel("data\Current-macroeconomic-situation-Tables-Based-on-Six-Month-data-of-2082.83.xlsx", sheet_name = 17,header=None)

df.head()

,0,1,2,3,4,5,6,7,8,9
0,NaN,Table 16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Exports of Major Commodities to China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,(Rs. in million),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,S.N.,Heading,2023/24R,NaN,2024/25R,NaN,2025/26P,Percent Change,NaN

In [51]:
#droping 0 index columns
df = df.drop(columns =[0])
df = df.iloc[7:].reset_index(drop=True) #dropping row to 6 th 

df.head(10)

,1,2,3,4,5,6,7,8,9
0,1,Agarbatti,20.438431,13.202302,24.357243,15.133183,8.204028,14.625336,-45.78782
1,2,Handicraft ( Metal and Wooden ),265.223273,187.45862,209.419099,162.091593,27.529957,-13.532067,-83.015802
2,3,Noodles,149.820742,140.901493,24.343494,8.444939,5.18868,-94.006494,-38.558704
3,4,Other handicraft goods,36.407459,18.671461,30.847542,16.876552,14.798347,-9.613114,-12.314156
4,5,Pashmina,35.424638,21.819445,52.822834,34.605776,25.477917,58.600623,-26.376692
5,6,Readymade Garments,160.052146,78.413285,150.373922,95.513652,73.131567,21.807997,-23.433388
6,7,Readymade Leather Goods,14.768903,14.447752,2.08658,1.015,0.441481,-92.974685,-56.504305
7,8,Rudrakshya,27.230936,16.941083,20.402769,13.67892,9.828602,-19.255925,-28.147825
8,9,Tanned Skin,12.195925,0,0,0,0,-,-
9,10,Tea,0.87098,0.81914,7.02218,7.02218,0.240011,-,-96.582097

In [52]:
df.shape #shape tell you number of row and columns

(14, 9)

In [53]:
print(df.columns) #list all column names

Index([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [54]:
print(len(df))

14

In [55]:
df.columns = [
    'S.N.',
    'Commodities',
    '2023/24 Annual',
    '2023/24 Six Months',
    '2024/25 Annual',
    '2024/25 Six Months',
    '2025/26 Six Months',
    '2024/25 Growth %',
    '2025/26 Growth %'
]
df.head()

,S.N.,Commodities,2023/24 Annual,2023/24 Six Months,2024/25 Annual,2024/25 Six Months,2025/26 Six Months,2024/25 Growth %,2025/26 Growth %
0,1,Agarbatti,20.438431,13.202302,24.357243,15.133183,8.204028,14.625336,-45.78782
1,2,Handicraft ( Metal and Wooden ),265.223273,187.45862,209.419099,162.091593,27.529957,-13.532067,-83.015802
2,3,Noodles,149.820742,140.901493,24.343494,8.444939,5.18868,-94.006494,-38.558704
3,4,Other handicraft goods,36.407459,18.671461,30.847542,16.876552,14.798347,-9.613114,-12.314156
4,5,Pashmina,35.424638,21.819445,52.822834,34.605776,25.477917,58.600623,-26.376692

In [60]:
df.describe()

print(f"Sum of 2024/25: {df['2024/25 Annual'].sum()}")     # add up the whole column → total exports that year
print(f"Mean of 2024/25: {df['2024/25 Annual'].mean()}")    # average value across commodities
print(f"Max of 2024/25: {df['2024/25 Annual'].max()}")     # the biggest single value
print(f"Min of 2024/25: {df['2024/25 Annual'].min()}")

Sum of 2024/25: 5260.0585802
Mean of 2024/25: 404.61989078461534
Max of 2024/25: 2630.0292901
Min of 2024/25: 0

In [ ]:
# import matplotlib.pyplot as plt

# # Make sure these columns are numeric first (safety check)
# numeric_cols = [
#     "2023/24 Annual", "2023/24 Six Months",
#     "2024/25 Annual", "2024/25 Six Months",
#     "2025/26 Six Months"
# ]
# df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors="coerce")


# # 1. HISTOGRAM — shows the shape of the distribution
# plt.figure(figsize=(10, 5))
# plt.hist(df["2024/25 Annual"], bins=15, color="skyblue", edgecolor="black")
# plt.title("Distribution of 2024/25 Annual Export Values")
# plt.xlabel("Export Value (Rs. million)")
# plt.ylabel("Number of Commodities")
# plt.show()

# # Compare two years side by side (overlaid)
# plt.figure(figsize=(10, 5))
# plt.hist(df["2023/24 Annual"], bins=15, alpha=0.5, label="2023/24 Annual", color="orange")
# plt.hist(df["2024/25 Annual"], bins=15, alpha=0.5, label="2024/25 Annual", color="skyblue")
# plt.title("Distribution Comparison: 2023/24 vs 2024/25")
# plt.xlabel("Export Value (Rs. million)")
# plt.ylabel("Number of Commodities")
# plt.legend()
# plt.show()


# # 2. BOX PLOT — spotting outliers and comparing spread
# plt.figure(figsize=(8, 6))
# df[["2023/24 Annual", "2024/25 Annual"]].plot(kind="box")
# plt.title("Box Plot: 2023/24 vs 2024/25 Annual Exports")
# plt.ylabel("Export Value (Rs. million)")
# plt.show()

# # All five value columns together
# plt.figure(figsize=(10, 6))
# df[numeric_cols].plot(kind="box")
# plt.xticks(rotation=30, ha="right")
# plt.title("Box Plot: All Export Value Columns")
# plt.ylabel("Export Value (Rs. million)")
# plt.tight_layout()
# plt.show()


# # 3. COEFFICIENT OF VARIATION (CV) — relative spread, so you can compare
# #    columns with very different scales (Annual vs Six Months)
# print("Coefficient of Variation (CV = std / mean)\n")

# for col in numeric_cols:
#     mean_val = df[col].mean()
#     std_val  = df[col].std()
#     cv = std_val / mean_val   # as a ratio
#     cv_pct = cv * 100         # as a percentage

#     print(f"{col}")
#     print(f"  Mean: {mean_val:.2f}   Std: {std_val:.2f}")
#     print(f"  CV:   {cv:.2f}  ({cv_pct:.1f}%)\n")

# # Sort columns by CV to see which is most "spread out" relative to its own mean
# cv_summary = {
#     col: df[col].std() / df[col].mean()
#     for col in numeric_cols
# }
# cv_series = pd.Series(cv_summary).sort_values(ascending=False)
# print("Columns ranked by relative spread (highest CV first):")
# print(cv_series)